--- 
name: nourish
email: steve@nourish.je
highlighter: rouge
image_folder: /assets/images
markdown: kramdown
timezone: Europe/London
upload_folder: /assets/uploads
git_repo: https://github.com/simlrh/nourish.je
gems: 
  - jekyll-textile-converter
  - jekyll-github-comments
exclude: 
  - node_modules
  - bower_components
  - src
  - package.json
  - Gruntfile.js
  - bower.json
  - s3_website.yml
  - semantic
github_comments:
  repo: simlrh/nourish.je
excerpt_separator: <!--more-->
collections: 
  articles:
    output: true
    permalink: "/:path/index.html"
  casestudies:
    output: false
  projects: 
    output: true
    permalink: "/:collection/:path/index.html"
  tumbles:
    output: true
    permalink: "/:collection/:path/index.html"
defaults: 
  - 
    scope: 
      path: ""
      type: tumbles
    values: 
      layout: post
  - 
    scope: 
      path: ""
      type: projects
    values: 
      layout: project
  -
    scope:
      path: ""
      type: articles
    values:
      layout: post
